import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../src/components/Layout/Layout'
import Career from '../src/containers/Career/Career'


const CareerPage: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Career</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Career/>
      </Layout>
    </div>
  )
}

export default CareerPage