import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../src/components/Layout/Layout'
import Contact from '../src/containers/Contact/Contact'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <Contact/>
      </Layout>
    </div>
  )
}

export default Home