import React from 'react';
import Head from 'next/head'
import Layout from '../src/components/Layout/Layout'
import Press from '../src/containers/Press/Press';



const press = () => {
    return (
        <>
            <Head>
                <title>News & Press</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Layout>
                <Press />
            </Layout>
        </>
    );
};

export default press;